name: consul
home: https://github.com/hashicorp/consul
version: 0.2.0
description: Hashicorp Consul Helm chart for Kubernetes.
icon: https://www.consul.io/assets/images/logo_large-475cebb0.png
sources:
  - https://github.com/kelseyhightower/consul-on-kubernetes
maintainers:
  - name: Lachlan Evenson
    email: lachlan@deis.com
